# Generated by Django 2.2 on 2019-04-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190408_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
