# Generated by Django 2.2 on 2019-05-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20190430_1314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente_sistema',
        ),
    ]
